### ISSUE TITLE
Build check 07/11/2023

### ISSUE THREAD

**Issue by ComercialNuruk** [RealityNearFoundation2022/Nuruk#10]
## Description
Transmission spots' validation layers. 

All the transmission spots has to be freed when the user stops broadcasting, but not in the first fashion of clicking the "Stop sharing" button, instead it has to be by force, quitting from the _game_ usually closing the browser pane or the browser itself.

## It's suppose to

Be successful in the next items:

- [x] Club del Bitcoin
- [x] Startups Latam
- [x] Zentral Market
- [x] Near Centre 
- [x] University (Exterior and Interior)
- [x] Yoga park
- [x] Open Web Academy

**Comment by u-m-i** [comment]
### Build target
[v.0.1.1-alpha](https://github.com/RealityNearFoundation2022/Nuruk/releases/tag/v.0.1.1-alpha)

**Comment by ComercialNuruk** [comment]
it was tested in different locations, it only worked correctly in the bitcoin club (force the website to close)
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/22381086-f3d3-4a71-96d3-30ef0803ad22)
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/b4fc6ce9-67ad-496f-93c7-fbefc4fdb733)

in all other points, when I wanted to start streaming, my avatar disappeared
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/82dc467f-2d67-44d2-a723-58496f50e09e)
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/6beea2ed-0247-4921-81b8-eef776e264d9)

**Comment by u-m-i** [comment]
_Hotfix on the way..._

**Comment by u-m-i** [comment]
## Build target

v.0.0.1-alpha-test

\<Client\> Run in the tester's Local Environment
\<Server\> Running independently

**Comment by ComercialNuruk** [comment]
when i take a sit i cant see the stream and i cant leave the chair this error occure in all nuruk
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/c84a5258-0566-40ce-b2e4-2be37452e401)

Near Centre all good but the streaming look like this
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/71e9662a-5b8e-4baf-8eaa-5ba230066c45)

Open web academy looks good but inverted 
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/44cf1954-2d4f-477e-8f0f-78f69a647f4a)
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/2db0362b-63d0-4e01-a8d0-d5647278c8d9)

Yoga park all good, but i did a test, opening another browser (chrome) and sharing another stream at the university and using the two domes of the yoga park, this is the result (image)
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/8736b7e6-a3da-4adb-b865-ced76d32012d)

now, when i wanted to stream on the dome (Yoga park) where i used my Chrome account, this is what happened with OperaGX
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/de841d01-168b-46bf-8c2c-fa8d9afcc171)

@u-m-i

**Comment by u-m-i** [comment]
## Build target

[v.0.0.1-alpha-test](https://github.com/RealityNearFoundation2022/Nuruk/releases/tag/v.0.1.1-alpha-test)

\<Client\> Run in the tester's Local Environment
\<Server\> Running independently 

\<Tester\> @ComercialNuruk

**Comment by ComercialNuruk** [comment]
I just entered nuruk, I did the usual thing, muted the microphone, the cursor with the letter T disappeared, I took a few steps and this message appeared
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/3ae15442-13d8-4c8b-be39-105430b2fb59)

**Comment by u-m-i** [comment]
_Hotfix on the way_

**Comment by u-m-i** [comment]
## Build target

[v.0.0.1-alpha-test](https://github.com/RealityNearFoundation2022/Nuruk/releases/tag/v.0.1.1-alpha-test)

\<Client\> Run in the tester's Local Environment
\<Server\> Running independently 

\<Tester\> @ComercialNuruk

**Comment by ComercialNuruk** [comment]
Near Centre looks good but inverted
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/be5bc03a-1fd2-4a9b-bbd2-941d485c4a43)

@u-m-i

**Comment by u-m-i** [comment]
## Build target

[v.0.0.1-alpha-test](https://github.com/RealityNearFoundation2022/Nuruk/releases/tag/v.0.1.1-alpha-test)

### Metadata

\<Client\> Run in the tester's Local Environment
\<Server\> Running independently 
\<Tester\> @ComercialNuruk 
\<Bugs\> Chair of dead, Inverted stream surface.

**Comment by ComercialNuruk** [comment]
Near Centre, the stream looks good

the death chair still works, pov no changes
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/f861df60-70b6-4669-9585-d324725b35e5)
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/de54207a-e0a3-46ef-a5e1-3d5f46616ac1)

**Comment by u-m-i** [comment]
## Build target

[v.0.0.1-alpha-test](https://github.com/RealityNearFoundation2022/Nuruk/releases/tag/v.0.1.1-alpha-test)
****

### Metadata

\<Client\> Run in the tester's Local Environment
\<Server\> Running independently 
\<Tester\> @ComercialNuruk 
\<Bugs\> Chair of dead.

**Comment by ComercialNuruk** [comment]
All good with the stream, there is no more deaths chairs, but...
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/a6ec98ec-69a1-4eb4-ab41-79351a5922a7)

![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/de4850cf-7bdb-48d6-96cf-c3d3cb3f414a)

![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/5f152ce1-a23b-4cb9-a312-60812ee14f01)

additional observation
![image](https://github.com/RealityNearFoundation2022/Nuruk/assets/140763141/5e9d83b6-2bed-49a0-8b9e-dbac78517694)

@u-m-i

**Comment by u-m-i** [comment]
## Build target

[v.0.0.1-alpha-test](https://github.com/RealityNearFoundation2022/Nuruk/releases/tag/v.0.1.1-alpha-test)
****

### Metadata

\<Client\> Run in the tester's Local Environment
\<Server\> Running independently 
\<Tester\> @ComercialNuruk 
\<Bugs\> Chair of dead, Different stream spots.

**Comment by u-m-i** [comment]
_Creating a separate issue for each bug_

**Comment by u-m-i** [comment]
[Incorrect point of view](https://github.com/RealityNearFoundation2022/Nuruk/issues/11)
[Mutliple users on the same chair](https://github.com/RealityNearFoundation2022/Nuruk/issues/12)

**Comment by ComercialNuruk** [comment]
Final review: @u-m-i @JBD84 

- [ ] All zones where can stream working

- [ ] Final testing when streaming and force the web to close still working for others users

- [ ] There is no chairs of the death, **but some ones chair can send us to other screen** (pending to check)

- [ ] Nuruk now can make multi streaming
